dev(dev): adding a prerequisites step

diff --git a/run.jmeter.kubernetes.template.yaml b/run.jmeter.kubernetes.template.yaml
--- a/run.jmeter.kubernetes.template.yaml
+++ b/run.jmeter.kubernetes.template.yaml
@@ -65,16 +65,23 @@ jobs:
 
             if [ "$check_arm_connection" == "true" ];then
                 if [ "$(armServiceConnection)" == "_" ];then
-                  echo "##[warning]ARM Connection is set to default '$(armServiceConnection)'. Please create a correct ARM connection to yoru resource group and update your pipeline. FAIL "
+                  message="ARM Connection is set to default '$(armServiceConnection)'. Please create a correct ARM connection to yoru resource group and update your pipeline"
+                  echo "##vso[task.logissue type=error]$message"
+                  exit 1
                 else
                   echo "##[command] OK"
                 fi
             fi
 
-
-            echo "ARM service connection: $(armServiceConnection)"
-            echo "K8 service connection: $(kubernetesServiceConnection)"
-
+            if [ "$check_k8_connection" == "true" ];then
+                if [ "$(kubernetesServiceConnection)" == "_" ];then
+                  message="ARM Connection is set to default '$(armServiceConnection)'. Please create a correct ARM connection to yoru resource group and update your pipeline"
+                  echo "##vso[task.logissue type=error]$message"
+                  exit 1
+                else
+                  echo "##[command] OK"
+                fi
+            fi
           displayName: Pipeline Configuration Requirements Check
 
     #DYNAMIC
